config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  resources :users, except: [:new, :create, :edit, :update, :destroy] do
    resources :posts do
      resources :comments, only: [:new, :create, :edit, :update, :destroy]
      end
    get :follow , on: :member
    get :unfollow, on: :member
    end
  end    

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates_presence_of :text
	validates_presence_of :post_id
	belongs_to :post
end 

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates_presence_of :name
	validates_presence_of :text
	validates_presence_of :user_id
	belongs_to :user
	has_many :comments, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #mount_uploader :avatar, AvatarUploader 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_uniqueness_of :name
  has_many :posts, :dependent => :destroy
  acts_as_followable
  acts_as_follower
  #mount_uploader :avatar, AvatarUploader
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!  
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password,
      :password_confirmation, :remember_me, :avatar, :avatar_cache) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password,
      :password_confirmation, :current_password, :avatar, :avatar_cache) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :load_user

	def new
		@com = Comment.new
	end

	def create
		@com = @post.comments.new params.require(:comment).permit(:text)
			if @com.save
				redirect_to user_posts_path(@user)
			else
				render :new
			end
	end

	private

		def load_user
			@user = current_user
 			@post = Post.find(params[:post_id])

		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :load_user
	
	def index
		@posts = Post.all.order('updated_at DESC')
	end
	
	def show
		@post  = Post.find(params[:id])
	end
	
	def new
		@post = Post.new
	end
	
	def create
		@post = @user.posts.new params.require(:post).permit(:text, :name)
			if @post.save
				redirect_to user_posts_path(@user)
			else
				render :new
			end
	end

	def edit
		@post = Post.find(params[:id])
	end
 	
 	def update
	    @post = Post.find params[:id]
	    if @post.update_attributes params.require(:post).permit(:user_id, :text, :name)
	      redirect_to user_posts_path(@user)
	    else
	      render :edit
	    end
  	end

	def destroy
		@post  = Post.find(params[:id])
		@post.destroy
    	redirect_to user_posts_path @user
	end

	private

		def load_user
			# ne plus utiliser pour prevent url rewriting
			# @user1 = User.find params[:id]
			@user = current_user
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
		@user = current_user
	end

	def show
		p "----------------------------------"
		p params
		p "----------------------------------"
		@user = User.find(params[:id])
		p @user

	end

	def follow
  		@user = User.find(params[:id])

  		if current_user
    		if current_user == @user
      			flash[:error] = "You cannot follow yourself."
      			redirect_to :back, :notice => "successfully followed someone..."
    		else
      			current_user.follow(@user)
      			flash[:notice] = "You are now following."
      			redirect_to :back, :notice => "successfully followed someone..."
    		end
  		else
    		flash[:error] = "You must <a href='/users/sign_in'>login</a> to follow.".html_safe
  			redirect_to :back, :notice => "successfully followed someone..."
  		end
	end

	def unfollow
  		@user = User.find(params[:id])

  		if current_user
    		current_user.stop_following(@user)
    		flash[:notice] = "You are no longer following ."
    		redirect_to :back, :notice => "successfully followed someone..."
  		else
    		flash[:error] = "You must <a href='/users/sign_in'>login</a> to unfollow.".html_safe
  			redirect_to :back, :notice => "successfully followed someone..."
  		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.haml
= simple_form_for [@user, @post, @com] do |com|
  .form_div
    %p
      = com.input :text, :label => false, :input_html => {:class => "form-control", :placeholder => "*Comment", :rows => "3"}
    %input.btn.btn-default{:type => "submit", :value => "Comment"}/

app/views/comments/new.html.haml
%h1.center_title
  Post a comment
  %small ...and prove them wrong
= render :partial => "form"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title JewtterV2
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    / ======================= NAV BAR ===========================
    - if current_user.present?
      %nav.navbar.navbar-inverse{:role => "navigation"}
        .container-fluid
          / Brand and toggle get grouped for better mobile display
          .navbar-header
            %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.navbar-brand ©Jewtter
          / Collect the nav links, forms, and other content for toggling
          #bs-example-navbar-collapse-1.collapse.navbar-collapse
            %ul.nav.navbar-nav
              - if current_user.id == @user.id
                %li= link_to "Profile" , user_path(@user)
                %li= link_to "Jewtter" , user_posts_path(@user)
              %li.dropdown
                %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                  Jewt
                  %span.caret
                %ul.dropdown-menu{:role => "menu"}
                  %li= link_to "jewtter", user_posts_path(@user)
                  - if current_user.id == @user.id
                    %li= link_to "New Jewt", new_user_post_path(@user)
            %ul.nav.navbar-nav.navbar-right
              %li= link_to "Sign out", destroy_user_session_path, :method => :delete
            %form.navbar-form.navbar-right{:role => "search"}
              .form-group
                %input.form-control{:placeholder => "Search", :type => "text"}
                  %button.btn.btn-default{:type => "submit"} Search
        / /.navbar-collapse
      / /.container-fluid
    / ======================= FIN NAV BAR ===========================
    = yield

app/views/posts/_form.html.haml
= simple_form_for [@user, @post] do |post|
  .form_div
    %p
      = post.input :name, :label => false, :input_html => {:class => "form-control", :placeholder => "*Title"}
    %p
      = post.input :text, :label => false, :input_html => {:class => "form-control", :placeholder => "*Content", :rows => "3"}
    %input.btn.btn-default{:type => "submit", :value => "Jewt"}/

app/views/posts/edit.html.haml
%h1.center_title
  Edit a Jewt
  %small ...and fix that nose
= simple_form_for [@user, @post] do |post|
  .form_div
    %p
      = post.input :name, :label => false, :input_html => {:class => "form-control", :placeholder => "*Title"}
    %p
      = post.input :text, :label => false, :input_html => {:class => "form-control", :placeholder => "*Content", :rows => "3"}
    %input.btn.btn-default{:type => "Submit", :value => "Submit Modifications"}/

app/views/posts/index.html.haml
%body
	%h1.center_title
		%small
			= "Welcome to"
			= "Jewtter"
	.detail_div
		- @posts.each do |post|
			%table.table.table-bordered.table-striped
				%tr
					%td.lead.title_and_jewt
						= link_to "Edit", edit_user_post_path(@user, post)
					%td
						= link_to post.name, user_post_path(@user, post)
						= "written by "
						= link_to post.user.name, user_path(post.user_id)
				%tr
					%td.lead.lead.title_and_jewt
						= link_to "Del", user_post_path(@user, post), :method => :delete, :data => {:confirm => 'Are you sure?'}
					%td
						= post.text
				%tr
					%td.lead.title_and_jewt
						= link_to "Com", new_user_post_comment_path(@user, post)
					%td
						- post.comments.each do |com|
							= com.text 

app/views/posts/new.html.haml
%h1.center_title
  Post a Jewt
  %small ...and make money
= render :partial => "form"

app/views/posts/show.html.haml
%h1.text-center.lead
	= "Details of " + @post.name 
.detail_div
	%table.table.table-bordered.table-striped
		%tr
			%td.lead
				= "Author"
			%td.lead
				= "Title"
			%td.lead
				= "Content"
			%td.lead
				= "Posted"
			%td.lead
				= "Last Update"

		%tr
			%td
				= link_to @post.user.name, user_path(@post.user)
			%td
				= @post.name
			%td
				= @post.text
			%td
				= @post.created_at.strftime("%d %b. %Y")
			%td
				= @post.updated_at.strftime("%d %b. %Y")

app/views/users/_follow_user.html.haml
- unless @user == current_user
  - if current_user.following?(@user)
    = link_to(unfollow_user_path(@user), :remote => true, :class => 'btn btn-primary') do
      %i.icon-remove.icon-white
      'Un-Follow'
  - else
    = link_to(follow_user_path(@user) ,:remote => true, :class => 'btn btn-primary') do
      %i.icon-ok.icon-white
      'Follow'

app/views/users/index.html.haml
%body
	%h1
		%p.center_title
			= "Welcome " + current_user.name
	%h1
		- if @user.posts.count != 0
			%p.center_title.small.lead
				= "Your last jewt: "
			%p.center_title.small
				= '"' + @user.posts.last.text + '"'
		- else
			%p.center_title.small
				= "Ready to post your first jewt ?"

app/views/users/show.html.haml
%body
	%h1.center_title
		%small
			= @user.name + "'s profile"
			- if current_user != @user
				- if current_user.following?(@user)
					= link_to "Unfollow", unfollow_user_path(@user)
				- else
					= link_to "Follow", follow_user_path(@user)

	.detail_div
		%table.table.table-bordered.table-striped
			%tr
				%td.lead
					= "name"
				%td.lead
					= "email"
				%td.lead
					= "Jewtter since"
				%td.lead
					= "Last time online"
				%td.lead
					= "Number of jewts"
				%td.lead
					= "follow"
				%td.lead
					= "followed by"
			%tr
				%td
					= @user.name
				%td
					= @user.email
				%td
					= @user.created_at.strftime("%d %b. %Y")
				%td
					= @user.last_sign_in_at.strftime("%d %b. %Y")
				%td
					= @user.posts.count
				%td
					- @user.all_following.each do | followed |
						= followed.name
				%td
					- @user.user_followers.each do | follower |
						= follower.name